### ISSUE TITLE
Error's with the latest version

### ISSUE THREAD

**Issue by daniel13306** [momo5502/s1x-server-scripts#1]
i had some errors after applying the newest version, here are some of them:

https://s12.directupload.net/images/210511/62ggrfyl.png

**Comment by momo5502** [comment]
Requires the latest develop build of s1x. You can either grab it from here (which I don't really recommend, as it's not as stable as release): https://master.xlabs.dev:444/s1x/develop/Release/build/bin/x64/Release/s1x.exe or you wait until the update is pushed.
