### ISSUE TITLE
s1x/scripts/bots/__init__.lua:46: attempt to call a nil value (method 'endon')

### ISSUE THREAD

**Issue by bloupotlood** [momo5502/s1x-server-scripts#2]
Thanks for the script!  But when I run the latest one, I get these errors:

s1x/scripts/bots/__init__.lua:46: attempt to call a nil value (method 'endon')
stack traceback:
	s1x/scripts/bots/__init__.lua:46: in function 'base.kickLeftoverBot'
	s1x/scripts/bots/__init__.lua:61: in function 'base.player_connected'
****************************************************
************** Script execution error **************
s1x/scripts/bots/__init__.lua:46: attempt to call a nil value (method 'endon')
stack traceback:
	s1x/scripts/bots/__init__.lua:46: in function 'base.kickLeftoverBot'
	s1x/scripts/bots/__init__.lua:61: in function 'base.player_connected'

**Comment by momo5502** [comment]
#1
